# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy

# command to install dependencies
install:
  - pip install -U tox

# command to run tests, e.g. python setup.py test
script: tox

# config to deploy in PyPI when a tag is pushed
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: scrapinghub/extruct
    condition: $TOXENV == py27
